package com.demo.common.model;

import com.demo.common.model.base.BaseContentType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContentType extends BaseContentType<ContentType> {
    public static final ContentType dao = new ContentType();
}
