package com.demo.common.model;

import com.demo.common.model.base.BaseContentType;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContentType extends BaseContentType<ContentType> {
	public static final ContentType dao = new ContentType();

	/**
	 * 查询菜单的子菜单
	 */
	public List<ContentType> getSubContentTypes() {
		return dao.find("select * from content_type where parent_id = ?", new Object[]{get("id")});
	}


}
