package com.demo.common.model;

import com.demo.common.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User();

    public Page<User> paginate(int pageNumber, int pageSize) {
        return paginate(pageNumber, pageSize, "select *", "from user order by id asc");
    }

    public String award() {
        if (this.getAwardType() == 1) {
            return "国家千人计划";
        } else if (this.getAwardType() == 2) {
            return "国家杰出青年基金获得者";
        } else if (this.getAwardType() == 3) {
            return "国家级教学名师";
        } else if (this.getAwardType() == 4) {
            return "国家优秀青年基金获得者";
        } else if (this.getAwardType() == 5) {
            return "教育部“新世纪人才”";
        } else if (this.getAwardType() == 6) {
            return "天津市千人计划";
        } else if (this.getAwardType() == 7) {
            return "天津市中青年科技创新领军人才";
        } else if (this.getAwardType() == 8) {
            return "天津市青年科技优秀人才";
        } else if (this.getAwardType() == 9) {
            return "天津市重点领域创新团队";
        } else if (this.getAwardType() == 10) {
            return "天津市青年拔尖人才";
        } else if (this.getAwardType() == 11) {
            return "万人计划";
        } else if (this.getAwardType() == 12) {
            return "天津市教学名师";
        } else if (this.getAwardType() == 13) {
            return "天津市131创新团队";
        } else if (this.getAwardType() == 14) {
            return "天津市131创新型人才工程第一层次";
        }
        return null;
    }

    public String laboratory() {
        if (this.getLaboratory() == 1) {
            return "新能源材料研究所";
        } else if (this.getLaboratory() == 2) {
            return "TJU-NIMS";
        } else if (this.getLaboratory() == 3) {
            return "焊接与先进制造研究所";
        } else if (this.getLaboratory() == 4) {
            return "先进高分子研究所";
        } else if (this.getLaboratory() == 5) {
            return "金属材料研究所";
        } else if (this.getLaboratory() == 6) {
            return "先进陶瓷研究所";
        }
        return "其他";
    }

}
