package com.demo.common.model;

import com.demo.common.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User();

    public Page<User> paginate(int pageNumber, int pageSize) {
        return paginate(pageNumber, pageSize, "select *", "from user order by id asc");
    }

    public String award() {
        if (this.getAwardType() == 1) {
            return "长江学者奖励计划";
        } else if (this.getAwardType() == 2) {
            return "国家重点基础研究发展规划(973)首席科学家";
        } else if (this.getAwardType() == 3) {
            return "国家杰出青年基金获得者";
        } else if (this.getAwardType() == 4) {
            return "国家千人计划入选者";
        }
        return null;
    }

    public String laboratory() {
        if (this.getLaboratory() == 1) {
            return "塑形成性技术与装备研究院";
        } else if (this.getLaboratory() == 2) {
            return "复合材料研究所";
        } else if (this.getLaboratory() == 3) {
            return "轻合金研究所";
        } else if (this.getLaboratory() == 4) {
            return "研究所4";
        }
        return null;
    }

}
